name: "Release Build"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up JDK 12
        uses: actions/setup-java@v3
        with:
          java-version: "12"
          distribution: "zulu"
      - uses: subosito/flutter-action@v2
        with:
          channel: "master"
      - name: Set up
        run: |
          flutter pub get
          sudo apt-get install rar
      - name: Build with Flutter
        run: |
          flutter build apk
          flutter build windows
      - name: Add version to APK
        run: mv "build/app/outputs/flutter-apk/app-release.apk" pyacine-tv-apk-${{ env.RELEASE_VERSION }}.apk
      - name: Create Archive
        run: rar a -r pyacine-tv-windows-${{ env.RELEASE_VERSION }}.rar "build/windows/runner/Release/"
      - name: Publish
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.RELEASE_VERSION }}
          prerelease: false
          files: |
            pyacine-tv-apk-${{ env.RELEASE_VERSION }}.apk
            pyacine-tv-windows-${{ env.RELEASE_VERSION }}.rar
